default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: toledoTournament_development

test:
  <<: *default
  database: toledoTournament_test

production:
  <<: *default
  database: toledoTournament_production
  username: toledoTournament
  password: <%= ENV['TOLEDOTOURNAMENT_DATABASE_PASSWORD'] %>
